# Generated by Django 3.2.18 on 2023-08-27 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkWod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark_wod',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assault_biking', models.BooleanField(default=None)),
                ('air_sqaut', models.BooleanField(default=False)),
                ('back_extension', models.BooleanField(default=False)),
                ('back_sqaut', models.BooleanField(default=False)),
                ('bear_crawl', models.BooleanField(default=False)),
                ('bench_press', models.BooleanField(default=False)),
                ('biking', models.BooleanField(default=False)),
                ('box_jump', models.BooleanField(default=False)),
                ('box_stepup', models.BooleanField(default=False)),
                ('broad_jump', models.BooleanField(default=False)),
                ('burpee', models.BooleanField(default=False)),
                ('c2b', models.BooleanField(default=False)),
                ('clean', models.BooleanField(default=False)),
                ('crossover', models.BooleanField(default=False)),
                ('curl', models.BooleanField(default=False)),
                ('deadlift', models.BooleanField(default=False)),
                ('devil_press', models.BooleanField(default=False)),
                ('dip', models.BooleanField(default=False)),
                ('double_under', models.BooleanField(default=False)),
                ('farmers_carry', models.BooleanField(default=False)),
                ('front_squat', models.BooleanField(default=False)),
                ('goblet_squat', models.BooleanField(default=False)),
                ('g2o', models.BooleanField(default=False)),
                ('hs_hold', models.BooleanField(default=False)),
                ('hspu', models.BooleanField(default=False)),
                ('hs_walk', models.BooleanField(default=False)),
                ('jerk', models.BooleanField(default=False)),
                ('kettlebell_swing', models.BooleanField(default=False)),
                ('l_sit', models.BooleanField(default=False)),
                ('lunge', models.BooleanField(default=False)),
                ('muscle_up', models.BooleanField(default=False)),
                ('ohs', models.BooleanField(default=False)),
                ('pistol', models.BooleanField(default=False)),
                ('pullup', models.BooleanField(default=False)),
                ('push_press', models.BooleanField(default=False)),
                ('pushup', models.BooleanField(default=False)),
                ('ring_row', models.BooleanField(default=False)),
                ('rope_climb', models.BooleanField(default=False)),
                ('row', models.BooleanField(default=False)),
                ('run', models.BooleanField(default=False)),
                ('s2o', models.BooleanField(default=False)),
                ('single_under', models.BooleanField(default=False)),
                ('situp', models.BooleanField(default=False)),
                ('ski', models.BooleanField(default=False)),
                ('sled_pull', models.BooleanField(default=False)),
                ('sled_push', models.BooleanField(default=False)),
                ('snatch', models.BooleanField(default=False)),
                ('snatch_balance', models.BooleanField(default=False)),
                ('shoulder_press', models.BooleanField(default=False)),
                ('sumo_dl_highpull', models.BooleanField(default=False)),
                ('thruster', models.BooleanField(default=False)),
                ('t2b', models.BooleanField(default=False)),
                ('v_up', models.BooleanField(default=False)),
                ('wallball_shot', models.BooleanField(default=False)),
                ('wall_walk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LikeWod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like_wod',
            },
        ),
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('cate_score', models.CharField(max_length=50)),
                ('cate_ppl', models.CharField(max_length=50)),
                ('cate_special', models.CharField(max_length=50)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='wods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('bookmark_users', models.ManyToManyField(blank=True, related_name='bookmark_wods', through='wods.BookmarkWod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wods', to='wods.wod')),
            ],
        ),
        migrations.CreateModel(
            name='WodExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.exercise')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod')),
            ],
        ),
        migrations.AddField(
            model_name='wod',
            name='exercises',
            field=models.ManyToManyField(through='wods.WodExercise', to='wods.Exercise'),
        ),
        migrations.AddField(
            model_name='wod',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_wods', through='wods.LikeWod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likewod',
            name='wod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod'),
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abike', models.BooleanField(default=False)),
                ('barbell', models.BooleanField(default=False)),
                ('bench', models.BooleanField(default=False)),
                ('bikeerg', models.BooleanField(default=False)),
                ('box', models.BooleanField(default=False)),
                ('d_ball', models.BooleanField(default=False)),
                ('dip_bar', models.BooleanField(default=False)),
                ('dumbbell', models.BooleanField(default=False)),
                ('ghd_machine', models.BooleanField(default=False)),
                ('gymnastic_rings', models.BooleanField(default=False)),
                ('jump_rope', models.BooleanField(default=False)),
                ('kettlebell', models.BooleanField(default=False)),
                ('wallball', models.BooleanField(default=False)),
                ('pullup_bar', models.BooleanField(default=False)),
                ('rope', models.BooleanField(default=False)),
                ('rower', models.BooleanField(default=False)),
                ('sandbag', models.BooleanField(default=False)),
                ('skierg', models.BooleanField(default=False)),
                ('sled', models.BooleanField(default=False)),
                ('treadmill', models.BooleanField(default=False)),
                ('wall', models.BooleanField(default=False)),
                ('weight_rack', models.BooleanField(default=False)),
                ('weight_vest', models.BooleanField(default=False)),
                ('worm', models.BooleanField(default=False)),
                ('wod', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='wods.wod')),
            ],
        ),
        migrations.AddField(
            model_name='bookmarkwod',
            name='wod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod'),
        ),
    ]
