# Generated by Django 3.2.18 on 2023-09-10 07:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkWod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark_wod',
            },
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='도구', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(default='target', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikeWod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like_wod',
            },
        ),
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('cate_score', models.CharField(blank=True, max_length=50, null=True)),
                ('cate_ppl', models.CharField(blank=True, max_length=50, null=True)),
                ('cate_special', models.CharField(blank=True, max_length=50, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='wods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('bookmark_users', models.ManyToManyField(blank=True, related_name='bookmark_wods', through='wods.BookmarkWod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wods', to='wods.wod')),
            ],
        ),
        migrations.CreateModel(
            name='WodExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.exercise')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod')),
            ],
        ),
        migrations.CreateModel(
            name='WodEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.equip')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod')),
            ],
        ),
        migrations.AddField(
            model_name='wod',
            name='equips',
            field=models.ManyToManyField(through='wods.WodEquip', to='wods.Equip'),
        ),
        migrations.AddField(
            model_name='wod',
            name='exercises',
            field=models.ManyToManyField(through='wods.WodExercise', to='wods.Exercise'),
        ),
        migrations.AddField(
            model_name='wod',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_wods', through='wods.LikeWod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likewod',
            name='wod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod'),
        ),
        migrations.AddField(
            model_name='bookmarkwod',
            name='wod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod'),
        ),
    ]
