# Generated by Django 3.2.18 on 2023-08-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0002_auto_20230827_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wod',
            name='cate_ppl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='cate_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='cate_special',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
