# Generated by Django 3.2.18 on 2023-08-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0003_auto_20230828_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wodexercise',
            old_name='exercise',
            new_name='exercises',
        ),
    ]
