# Generated by Django 3.2.18 on 2023-08-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0004_rename_exercise_wodexercise_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='abike',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='barbell',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='bench',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='bikeerg',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='box',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='d_ball',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='dip_bar',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='dumbbell',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='ghd_machine',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='gymnastic_rings',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='jump_rope',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='kettlebell',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='pullup_bar',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='rope',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='rower',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='sandbag',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='skierg',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='sled',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='treadmill',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='wall',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='wallball',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='weight_rack',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='weight_vest',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='wod',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='worm',
        ),
        migrations.AddField(
            model_name='equip',
            name='name',
            field=models.CharField(default='도구', max_length=100),
        ),
        migrations.CreateModel(
            name='WodEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.equip')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wods.wod')),
            ],
        ),
        migrations.AddField(
            model_name='wod',
            name='equips',
            field=models.ManyToManyField(through='wods.WodEquip', to='wods.Equip'),
        ),
    ]
