# Generated by Django 3.2.18 on 2023-09-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='visibility',
            field=models.CharField(default='비공개', max_length=20),
        ),
    ]
