# Generated by Django 3.2.18 on 2023-09-05 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='illness_range',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
    ]
