# Generated by Django 3.2.18 on 2023-09-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20230910_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='new_date',
            field=models.CharField(default='20230910', max_length=8, unique=True),
        ),
    ]
